### ISSUE TITLE
hassio addon problems

### ISSUE THREAD

**Issue by danielperna84** [danielperna84/hass-configurator#107]
1. The new version doesn't preprend `/ssl/` to the certificate anymore. Now that everybody is fixing this manually I'm not sure though if the previous implementation should be restored.
2. As mentioned [here](https://community.home-assistant.io/t/configurator-stopped-working-after-update-to-1-0/62582/39), the list of allowed networks under some circumstances can't be empty.

**Comment by danielperna84** [comment]
So apparently [this](https://github.com/home-assistant/hassio-addons/commit/3219d692f2e313e3345d0f76049a435c0502428b) has reverted the implementation to the old way, so no `/ssl` needed anymore.

**Comment by danielperna84** [comment]
Closing this because #108 and #109 are the actual bugs.

**Comment by paolo-pr** [comment]
I downloaded  the addon through the addon store of hassio about 15 days ago (then I presume it's a recent version, given that there's no info about the version on the hassio interface).
Then I tried with:

  "certfile": "/config/ssl/certificate.pem",
  "keyfile": "/config/ssl/privkey.pem",

as well as with  "config/certificate.pem",  "certificate.pem", "/config/certificate.pem", "/config/ssl/certificate.pem". And I put the certificates both at the same level of "configuration.yaml" and inside a directory called ssl at the same level of configuration.yaml.

None of these path seems to work. Please can you tell me what to write in "certfile" and "keyfile" and how these paths must be interpreted?
It would be necessary, I think, if you add these explanations on the documentation page, otherwise configuring the module is very frustrating.

Thank you
