### ISSUE TITLE
Configurator won't open UI

### ISSUE THREAD

**Issue by SirJMD** [danielperna84/hass-configurator#114]
Configurator 1.1
Hass.io supervisor Version 125
HassOS 1.9 (32 bit)
Home Assistant 0.75.3

Running on a RPi 3 B+ with a 32GB micro-SD card.

Log:
`INFO:2018-08-10 13:03:15,161:__main__:Starting server
WARNING:2018-08-10 13:03:15,162:__main__:Password PASSWORD does not contain digits
INFO:2018-08-10 13:03:15,173:__main__:{'title': 'HASS Configurator - Password warning', 'message': 'Your PASSWORD seems insecure (2). Refer to the HASS configurator logs for further information.', 'notification_id': 'HC_PASSWORD'}
INFO:2018-08-10 13:03:15,300:__main__:Listening on: http://0.0.0.0:3218`

(that password warning is rather annoying.. So my 25+ character pass is insecure because I didn't put a number in there. I guess Test1234 would be better? Would be nice to be able to disable that message..)

**Comment by danielperna84** [comment]
There is an open PR that fixes some issues that, depending on your configuration, may lead to this problem: https://github.com/home-assistant/hassio-addons/pull/368

Regarding the password-check: it's a rather basic check. But a mixture of letters and digits generally is accepted as more secure. That's why the configurator warns about this. The check happens in multiple steps, which is why even with a high length missing numbers are considered a problem.
I do understand it may be annoying. But you only get the message once every time the configurator is started. So if you dismiss it now and don't restart it for a while, you won't be bugged by it anymore.

Having seen the threads in the forum about people having exposed their samba share I think the greater value lies in telling people their passwords are insecure, compared to now and then dismissing a notification.

**Comment by danielperna84** [comment]
The new version has been release for hassio. Please confirm if the issue persists.

**Comment by danielperna84** [comment]
Any news on this?

**Comment by SirJMD** [comment]
Sorry for the late reply, the weekend has been crazy.

Having done absolutely nothing, the issue has now resolved itself.. a bit odd. What caused the configurator to point at 0.0.0.0, I don't know.

Regarding password entropy: lenght > complexity.

**Comment by danielperna84** [comment]
> lenght > complexity

Generally I agree on that. But the logic of the password check goes through several steps, where one of those is to see if numbers are included. Every step adds to the final error message. Complexity is checked as well. But that's a different step. And good complexity doesn't undo a previously failed check.
That being said, other products enforce usage of numbers too. Either by design or policy. If your employer uses Active Directory and says numbers are mandatory, then they are. No matter how long your password is. So if you are annoyed by it, set the service to `false`. That should disable the notification.
