### ISSUE TITLE
SESAME&SESAME_TOTP_SECRET doesn't work 

### ISSUE THREAD

**Issue by leranp** [danielperna84/hass-configurator#122]
there is no error message, only the login message appear.
pi@raspberrypi:/home/homeassistant/.homeassistant $ sudo python3 configurator.py settings.conf
INFO:2018-10-06 11:21:14,778:__main__:Starting server
INFO:2018-10-06 11:21:14,782:__main__:Listening on: https://192.168.31.100:3218
INFO:2018-10-06 11:21:21,203:__main__:192.168.31.224 - "GET / HTTP/1.1" 200 -
WARNING:2018-10-06 11:21:21,225:__main__:Exception getting bootstrap
WARNING:2018-10-06 11:21:21,225:__main__:Remote end closed connection without re

{
    "LISTENIP": "192.168.31.100",
    "PORT": 3218,
    "GIT": false,
    "BASEPATH": "/home/homeassistant/.homeassistant",
    "ENFORCE_BASEPATH": true,
    "SSL_CERTIFICATE": "/etc/letsencrypt/live/domain.duckdns.org/fullchain.pem",
    "SSL_KEY": "/etc/letsencrypt/live/domain.duckdns.org/privkey.pem",
    "IGNORE_SSL": true,
    "HASS_API": "http://127.0.0.1:8123/api/",
    "HASS_API_PASSWORD": null,
    "USERNAME": "admin",
    "PASSWORD": "pass",
    "ALLOWED_NETWORKS": [],
    "BANNED_IPS": [],
    "BANLIMIT": 0,
    "IGNORE_PATTERN": ["secrets.yaml"],
    "DIRSFIRST": false,
    "SESAME": "test",
    "SESAME_TOTP_SECRET": "IU2FV5EBE4IFSAIJ",
    "VERIFY_HOSTNAME": null,
    "ENV_PREFIX": "HC_",
    "NOTIFY_SERVICE": "persistent_notification.create"

**Comment by danielperna84** [comment]
I'm not sure what this issue is about.

The part of you log is showing, that the configurator is unable to connect to your Home Assistant instance. This has nothing to do with the `SESAME` or `SESAME_TOTP_SECRET`. These options also do not disable the authentication by username + password. They are just intended to allow access from unknown IP addresses which otherwise would be rejected. And since you say you are being prompted for the username and password, the IP check is bypassed correctly. So there's no obvious issue in regard to that option.

**Comment by leranp** [comment]
The SESAME_TOTP_SECRET isn't working also when i trying to login with unknown IP addresses, the only option for me is the login windows with user and password, i don't see any option to enter the 6 digits from the google app

**Comment by danielperna84** [comment]
You are misunderstanding what the `SESAME` and `SESAME_TOTP_SECRET` are used for. You are not supposed to see any login form to enter the code. It's for whitelisting client IP addresses that are trying to open the configurators UI. I'll try to summarize what it does.

1. By setting the `allowed_networks` to an empty list you prohibit __every__ connection to the configurator. This is useful when the configurator is exposed to the web.
2. Since you currently can not open the UI (should be error 420, policy not fulfilled), you need some way of telling the configurator that you are authorized and your client IP should be unblocked so you can proceed with regular authentication.
3. Here's where the `SESAME` comes into play. Let's say you access the configurator via `https://yourdomain.example.com:3218`. Without the `SESAME` you get the error and can't do anything. But if you browse to `https://yourdomain.example.com:3218/yoursecretsesame` (whatever you define the sesame to be), then your client IP gets whitelisted and you are asked for the username and password.
4. Since the `SESAME` is static it can be brute forced. Also it might be annoying to type in. That's where the TOTP-variant is useful. With TOTP enabled you memorize the token from the Authenticator app (`123456` for example) and then browse to `https://yourdomain.example.com:3218/123456`. This again whitelists access from your client IP, allowing you again to enter your username and password. Since the TOTP changes every 30 seconds you have to be quick when doing this. But the upside is, that an attacker won't have a lot of time to brute force a valid TOTP code to whitelist his own IP address.

That being said, the fact you are getting the prompt for the username and password tells me, that your client IP is already whitelisted. You only would need one of the sesame-variants if you get the 420 error.

**Comment by leranp** [comment]
Thank you very much for the information, now it is clear for me , thanks again!
