### ISSUE TITLE
Hass blank page

### ISSUE THREAD

**Issue by platini76** [danielperna84/hass-configurator#126]
hello, if I connect configurator from his page it work well with ssl ok

when ipanel_frame is enabled it always say connection not secure...

Uncaught (in promise) TypeError: Failed to execute 'fetch' on 'ServiceWorkerGlobalScope': 'only-if-cached' can be set only with 'same-origin' mode
    at Object.<anonymous> (/frontend_latest/workbox-v3.5.0/workbox-core.prod.js:1)
    at Generator.next (<anonymous>)
    at n (/frontend_latest/workbox-v3.5.0/workbox-core.prod.js:1)
    at /frontend_latest/workbox-v3.5.0/workbox-core.prod.js:1
workbox-core.prod.js:1 Uncaught (in promise) TypeError: Failed to execute 'fetch' on 'ServiceWorkerGlobalScope': 'only-if-cached' can be set only with 'same-origin' mode
    at Object.<anonymous> (workbox-core.prod.js:1)
    at Generator.next (<anonymous>)
    at n (workbox-core.prod.js:1)
    at workbox-core.prod.js:1

**Comment by platini76** [comment]
I think it is problem of ssl config....

{
    "LISTENIP": "0.0.0.0",
    "PORT": 3218,
    "GIT": false,
    "BASEPATH": null,
    "ENFORCE_BASEPATH": false,
    "SSL_CERTIFICATE": /home/homeassistant/dehydrated/certs/platini76.duckdns.org/fullchain.pem,
    "SSL_KEY": /home/homeassistant/dehydrated/certs/platini76.duckdns.org/privkey.pem,
    "IGNORE_SSL": false,
    "HASS_API": "http://127.0.0.1:8123/api/",
    "HASS_API_PASSWORD": null,
    "USERNAME": *********,
    "PASSWORD": *********,
    "ALLOWED_NETWORKS": [],
    "BANNED_IPS": [],
    "BANLIMIT": 0,
    "IGNORE_PATTERN": [],
    "DIRSFIRST": false,
    "SESAME": null,
    "SESAME_TOTP_SECRET": null,
    "VERIFY_HOSTNAME": null,
    "ENV_PREFIX": "HC_",
    "NOTIFY_SERVICE": "persistent_notification.create"
}

**Comment by platini76** [comment]
the error is: ERR_SSL_PROTOCOL_ERROR

**Comment by danielperna84** [comment]
What kind of certificate are you using? One from LetsEncrypt? The URL for the panel_iframe has to be the same as the URL your certificate is issued for. So you can't set the panel to some internal address of your network. Home Assistant won't load panels where the certificate verification fails (which is the case when you are not using the correct hostname).

**Comment by platini76** [comment]
solved!!! thanks....very much for your suggestion.
how can I protect it?

**Comment by danielperna84** [comment]
> how can I protect it?

What do you mean by that?

> there is a simple guide to set api?

This totally depends on your setup / kind of Home Assistnat installation. I suggest to read through the [README](https://github.com/danielperna84/hass-configurator/blob/master/README.md), and if that doesn't answer your questions have a look at the [community](https://community.home-assistant.io/).
The main problem you are facing right now is that the configurator doesn't get access to the HASS API. For this to work you have to properly set the API endpoint and the API password. If you are on a HASS release above 0.79, then you need to have the legacy API enabled. The next version of the configurator will support the usage of the new long-lived access tokens.

**Comment by platini76** [comment]
with protect I mean... which is the best (and noob setup) protection for hass-configurator that don't allow external bot to access to it?

**Comment by danielperna84** [comment]
Set a [username](https://github.com/danielperna84/hass-configurator/blob/master/README.md#username-string) and password, restrict the [allowed_networks](https://github.com/danielperna84/hass-configurator/blob/master/README.md#allowed_networks-list) to those you expect to access the configurator from, whitelist external IPs by using the [sesame](https://github.com/danielperna84/hass-configurator/blob/master/README.md#sesame-string) or [sesame_totp](https://github.com/danielperna84/hass-configurator/blob/master/README.md#sesame_totp_secret-string) function and enforce that the client has to use the correct [hostname](https://github.com/danielperna84/hass-configurator/blob/master/README.md#verify_hostname-string).

Althouch the ideal setup would be not to expose the configurator to the outside at all. Imagine modifying your configuration and breaking something while doing that. If you're not at home you'll have trouble fixing that. I wouldn't even use the panel_iframe because it takes away some space on your screen when the navigation on the left is still visible. And without the panel_iframe the SSL trouble from above is irrelevant because you're accessing the configurator directly.

Beyond that, please ask such questions in the community as well.

**Comment by platini76** [comment]
I won't modify my config when I am out home... only at home.
I setup a username and password
ALLOWED_NETWORKS = ["0.0.0.0/0"]  I see that only this config work on ssl... if I put my local ip doesn't work
maybe I have to set sesame...but I dont' know this function at all...

I have also difficoulties to understand how to set api
