### ISSUE TITLE
Won't autostart

### ISSUE THREAD

**Issue by TheZoker** [danielperna84/hass-configurator#127]
I activated the autostart button, but after rebooting the Raspi, the configurator is not running:
![screenshot_2018 11 06_23h45m22s_004_](https://user-images.githubusercontent.com/1368405/48196511-0b873080-e353-11e8-89b0-187b2226ec59.png)

I could not find any issue in the logs. All other addons (like mosquitto, ssh...) start fine
I did a fresh install like three days ago, but still the same issue...

- Hass.io: 0.82.0b3
- Supervisor: 139
- HassOS: 1.12

If you need more information, let me know :)

**Comment by danielperna84** [comment]
Please open a thread in the hassio-section of the [community](https://community.home-assistant.io/c/hass-io). Since I have never heard of such an issue (and the latest release is out for several months now), this is probably related to the system in general. Other hassio users may be able to help here (I'm not a hassio user).
