### ISSUE TITLE
Can the Hass.io Configurator add-on use an alternative port?

### ISSUE THREAD

**Issue by michthom** [danielperna84/hass-configurator#140]
I understand that the LISTENPORT variable allows for changing the default port (3218) to something else for manual Configurator installations on other platforms, but from the Hass.io [Configurator add-on page](https://www.home-assistant.io/addons/configurator/) I don't see a way to change that functionality?
I'd like to have two instances of Home Assistant on the same local network, but want to use Configurator on either one from a remote location, without having to switch the target of the port forwarding on my router to point to the desired instance.
Yes, I could also use different external ports but forward each to 3218 on the two instances, so this isn't a huge issue, it just seemed odd that the option doesn't seem to be available in the config of the add-on?
Cheers
Mike

**Comment by danielperna84** [comment]
This is not configurable for the addon, since within a Docker container there won't be any conflicts with ports other processes might be using. And hassio aims to be easy to configure, rather than flexible. That's why generally there are fewer options available.

You can however work around this problem by building your own fork the addon. The configurator also is available outside of the official repository: https://github.com/danielperna84/hassio-addons/
If you fork this repository you can change the port [here](https://github.com/danielperna84/hassio-addons/blob/810befae1e1b90356b5a4d2e732fe0bd8fffcbfd/hass-configurator/config.json#L12). And probably hardcode it for the configurator itself as well.

The interesting question would be, if hassio in general should receive an option to actually customize the ports where addons are listening. The port within the container doesn't matter after all. It's the port in the `config.json` that's responsible for which port the service ends up running on. So even with the option to change the port within the addon, the forwarding into the container would be broken then. That's something the hassio supervisor has to implement.
