### ISSUE TITLE
Still problems with certificates' paths

### ISSUE THREAD

**Issue by paolo-pr** [danielperna84/hass-configurator#144]
I downloaded the addon through the addon store of hassio about 15 days ago (then I presume it's a recent version, given that there's no info about the version on the hassio interface).
Then I tried with:

"certfile": "/config/ssl/certificate.pem",
"keyfile": "/config/ssl/privkey.pem",

as well as with "config/certificate.pem", "certificate.pem", "/config/certificate.pem", "config/ssl/certificate.pem". And I put the certificates both at the same level of "configuration.yaml" and inside a directory called ssl at the same level of configuration.yaml.

None of these path seems to work. Please can you tell me what to write in "certfile" and "keyfile" and how these paths must be interpreted?

Here's the conf file:

{
  "username": "admin",
  "password": "s0m3password",
  "ssl": true,
  "certfile": "one of the patsh written before",
  "keyfile": "one of the patsh written before",
  "allowed_networks": [],
  "banned_ips": [
    "8.8.8.8"
  ],
  "banlimit": 0,
  "ignore_pattern": [
    "__pycache__"
  ],
  "dirsfirst": false,
  "enforce_basepath": false,
  "notify_service": "persistent_notification.create"
}

It would be necessary, I think, that you add these explanations on the documentation page, otherwise configuring the module is very frustrating.

Thank you

**Comment by danielperna84** [comment]
> And I put the certificates both at the same level of "configuration.yaml" and inside a directory called ssl at the same level of configuration.yaml.

I don't usw hassio, so I'm not really sure about this. But those places sound wrong to me. No other addon would probably expect the certificates there. So you'll probably get the same problem with other addons too.

To my knowledge, `/ssl` is a separate folder outside of the regular configuration folder. Since I don't know much about that please head over to community.home-assistant.io where people can help you.

**Comment by paolo-pr** [comment]
In any case, the documentation is not clear.

"SSL_CERTIFICATE / SSL_KEY (string)
If you're using SSL, set the paths to your SSL files here. This is similar to the SSL setup you can do in Home Assistant."

What kind of path is it? Absolute? Relative? Relative to what? Is it only the filename?

Please fix that, otherwise it could be very frustrating to "guess" what an user must write there

**Comment by danielperna84** [comment]
Am I correct that you are referring to [this](https://www.home-assistant.io/docs/ecosystem/hass-configurator/) documentation? That's targeted at standalone installalations made from this repository. In this case the description is perfectly fine because without hassio it really is different from system to system. And here it's the absolute path.

For hassio the correct documentation can be found here: https://www.home-assistant.io/addons/configurator/
[Here](https://www.home-assistant.io/addons/configurator/#certfile) it says:
`(string)(Required) Set the path the your SSL certificate if the ssl-option is set to true.`

The part that resolves this configuration option looks like this:
`export HC_SSL_CERTIFICATE=ssl/$(jq --raw-output '.certfile' $CONFIG_PATH)`
So it assumes you have placed you certificate and key exactly there where they are saved by default. You just have to adjust the filenames in case you customized that. For pretty much everybody else it's just clicking the save-button and it works.

I do not know where exactly that ssl-folder is. I don't use hassio. I assume you will see it if you enable the Samba addon and browse to that.

If you think the documentation (for the __hassio addon__) needs to be improved, the correct repository to file an issue would be here: https://github.com/home-assistant/home-assistant.io. This repository is about the application itself.

**Comment by paolo-pr** [comment]
First of all, it's always better (if not even necessary) to specify, in the documentation, if a path is absolute or relative. I suggest you to do that. Adding the "absolute" word to the documentation of the field is zero-cost.

In addition, given that the name of this plugin is "hass configurator" both for hassio and home-assistant, and the description of each field matches as well, I assumed as default that the path was relative to the config directory, through some environment variable. Nobody can imagine that a plugin with the same name and same fields  has different settings if it belongs to hassio or home assistant.
I understand that the hassio staff sould improve the documentation, but if you make a more portable solution, with a path relative to some directory pointed by an env variable AND with the possibility to set an absolute path, all these problem would disappear.
