### ISSUE TITLE
HA configurator for Docker

### ISSUE THREAD

**Issue by max-rh** [danielperna84/hass-configurator#152]
Hello,
I have been using HA configurator for docker, and it has been working fine till the latest update;
My HA docker is running the latest HA 0.91, but the latest HA configurator failed to run with the following error:
/run.sh: line 12: HASSIO_TOKEN: unbound variable

any advice ?

**Comment by danielperna84** [comment]
Which Docker image did you use? Or do you use hassio? The `HASSIO_TOKEN` only is part of the hassio-addon, not the regular Docker image.
In case you are using hassio and the addon from the official addon repository: that hasn't been updated since November last year. So it should work as before. If you installed the addon from my repository, then there might be a but.
But if you are using a regular installation with regular Docker, you have to use [this](https://hub.docker.com/r/causticlab/hass-configurator-docker/) image. If that's what's causing trouble, please file an issue [here](https://github.com/CausticLab/hass-configurator-docker).
You can also build the image yourself with [this](https://github.com/danielperna84/hass-configurator/blob/master/Dockerfile) from this repository. It doesn't use the `HASSIO_TOKEN` for sure.

**Comment by max-rh** [comment]
Hi Daniel,
I have been using this HA image "homeassistant/home-assistant" and been using the corresponding configurater image from the same docker repository ever since, its just stopped working after the latest upgrade and the Token error appeared.

**Comment by danielperna84** [comment]
You mean _homeassistant/...-addon-configurator_? It says _addon_ in the name, so it's an addon for hassio. If you don't use hassio, then it's not the correct version for you. If it did work in the past you just had luck. It's tailored specifically for hassio and lacks configuration options. You should __NOT__ use that image when you don't use hassio.
For a regular Docker installation use, as mentioned in my previous answer, [this](https://hub.docker.com/r/causticlab/hass-configurator-docker/) image, or build it locally using [this](https://github.com/danielperna84/hass-configurator/blob/master/Dockerfile) dockerfile. Everything else is not supported by me.

**Comment by max-rh** [comment]
Thanks daniel, used the image u suggested, its working fine now; thanks alot.
