### ISSUE TITLE
How to use long lived token for accessing HA

### ISSUE THREAD

**Issue by dm82m** [danielperna84/hass-configurator#156]
Hey guys,

I created a long lived token and added it like that to the configuratror:
`HASS_API_PASSWORD = "my_token"`

But I am not able to reload automations or something like that out of the configurator?

What am I doing wrong?

Best,
Dirk

**Comment by danielperna84** [comment]
I assume you also do not see your entities, services etc. in the menu on the left then. Because if you see them, then the problem is not related to authentication, because services are called with the same token.

Please post the log-output of the configurator for the time in which the request to reload automations fails.

**Comment by dm82m** [comment]
Got it working, your hint regarding a look into the log was good ;-)

Problem was, that the log said:
`Apr 13 10:48:34 hassbian python3[545]: WARNING:2019-04-13 10:48:34,812:__main__:hostname '127.0.0.1' doesn't match 'domain.duckdns.org'`

So I set:
`HASS_API = "https://domain.duckdns.org/api/"`

And now everything works! :)
