### ISSUE TITLE
GIT repository path fail

### ISSUE THREAD

**Issue by pejotigrek** [danielperna84/hass-configurator#178]
ok, so I was pointed here from the [Hass.io addons repo issues directory](https://github.com/home-assistant/hassio-addons/issues/949) with the informations that it's probably the Configurator's issue itself. here's my situation:

Configurator: **4.2**
System: **HassOS 3.7**
HomeAssistant: **0.102.3** _[update pending - I need to make some changes to yaml, but this is not relevant to the issue]_
Hass.io supervisor: **193**
Hardware: **RaspberryPi3**

I have my hassio's samba share mapped to a windows drive letter. so whenever I want to access the `/config/` directory, I just go to the "disk" `A:/`
I use GitHub Desktop & my git repository is pointed to the `A:/` - and this is the root directory. I'm guessing, that Configurator can't understand this while reading git configuration files and this makes files read impossible; also when I try to see the files/folders structure in Configurator - there's nothing to see; and the `branch` pull-down list is empty. below you can find my Configurator's log:

```
INFO:2019-12-26 23:08:07,455:hass_configurator.configurator:Starting server
INFO:2019-12-26 23:08:07,457:hass_configurator.configurator:Listening on: http://0.0.0.0:8099
INFO:2019-12-26 23:08:34,444:hass_configurator.configurator:172.30.32.2 - "GET / HTTP/1.1" 200 -
INFO:2019-12-26 23:08:36,824:hass_configurator.configurator:172.30.32.2 - "GET /api/listdir?path=. HTTP/1.1" 200 -
WARNING:2019-12-26 23:08:36,866:hass_configurator.configurator:Cmd('git') failed due to: exit code(128)
  cmdline: git status --porcelain --untracked-files
  stderr: 'fatal: cannot chdir to 'a:/': No such file or directory
```

is there anything that can be done about it?

**Comment by danielperna84** [comment]
As guessed in the other issue already, this is not a problem with the configurator. I'm not a git-expert, but as far as I know git has no concept of drive letters. In a repository it only knows about the base directory and child directories. A reference to `a:/` makes no sense with git. Furthermore, in Windows paths use a backslash. So even if git would know about drive letters, it should be `a:\` instead.

The configurator probably doesn't show anything useful because it _crashes_ before it can evaluate the content of the directory.

I don' know what the solution to your problem is. But I can say for sure, that it is caused by you mix of Windows and Linux (which hassio is based on). If you don't mind losing your git history, you could remove the `.git` folder you should find in your config-directory. This essentially resets everything related to git. After that, the configurator should be able to display the content of the directory. Once that is done you can initialize your config-folder as a git-repository within the configurator. After that, you can try to open your mapped drive again within GitHub Desktop. The downside to this would be, that without additional work you won't be able to push your changes to GitHub.

In any case, your repo seems to be broken in some way. Maybe it is possible to fix this without losing the old commits. But someone with deeper git-knowledge would have to help you with that.

**Comment by pejotigrek** [comment]
thanks for detailed explaining!

yes, at the first time I thought it's something with Git [I'm totally not an expert in that too ;)] and I did _rebuild my repo_ starting almost from scratch [I was migrating to a new one, so I wasn't too attached to all the commits history anyway]. but it didn't helped.

"official" git software, such as Git Gui [stock, installed with Git on windows] and GitHub Desktop [additional] work with no problems [well, GitHub Desktop has it's issues, but it's purely beta-version related and has nothing with Git or my repo] - that's why I started to think that it is something wrong on the addon/configurator side. especially that there was a short period of time [unfortunately I can't even remember what versions were installed then] when Configurator worked fine with the same setup.

on the side note - as for my win&lin mixture - got plenty of linux-based stuff in my network that share some folders [NAS devices, "pure" linux PC, few RPis, routers with custom firmware etc.] and it works fine in other situations. I'm not an expert with linux, but with a little help of google I managed to configure my whole LAN in way that every device "can speak" and is "able to understand" eachother when needed - and most, if not all shares are mapped to letters on windows, for sake of comfortable access; but sure, there's a possibility that if Git saves the `A:\` path somewhere, it can cause issues.

before someone with greater git-knowledge joines in, **I'm going to think out loud**:
assuming that Configurator is basing on what it can read from config in the `.git` folder, would it be possible to add some config switch to force override the path of local repo? so instead of searching the wronged `A:/` Configurator would look for `/config/` [or whatever I'll enter?]

**Comment by danielperna84** [comment]
> "official" git software, such as Git Gui [stock, installed with Git on windows] and GitHub Desktop [additional] work with no problems

I assume they work on the machine where the share is also mounted as drive `a:\`. It will probably stop working there as well as soon as you change the drive letter. And that's the main issue. Git repositories store code and should be _valid_ within themselves by not referencing resources that aren't guaranteed to exist across different machines. Lets say you get a new computer and try to clone your repo in its current state without preparing the shares. You will for sure run into problems.

> especially that there was a short period of time [unfortunately I can't even remember what versions were installed then] when Configurator worked fine with the same setup.

This leads me to believe that the source of the problem is a commit that references a full path, even though it shouldn't. My first though would be the `.gitignore` file. There you specify paths that the repo should exclude from monitoring. If in there you have specified a path that includes the drive-letter, it could be a potential cause of the problem.

In general mixing Windows and Linux indeed works usually. It's specific to your setup where for some reason it tries to evaluate an absolute path to a drive that doesn't exist. Keep in mind, the repository you are looking at when using the configurator is located on the hassio-machine. The hassio-machine does not have a `a:\` drive. That's why you get the error.

Regarding your thought:  
As mentioned before, I'm fairly sure git does not have any concept of drives or absolute paths. If you create a repository in folder _xyz_, then internally it just references this as `.`, which in Linux the current directory. If there are subfolders, it will reference them as `./subfolder` etc. If it wasn't like that, the whole concept of cloning repositories wouldn't work. Imagine everyone working on Home Assistant would have to set up a virtual drive `z:\` just because one of the developers chose to store something there. As I have said, git-repos are self-contained and have to _work_ anywhere.

Just as a simple test, please move the `.git` folder somewhere else and see if the configurator starts displaying the files. This would at least verify, that the problem is directly related to your repos metadata. After that, look at `.gitignore` files and check you don't use absolute paths there.

**Comment by pejotigrek** [comment]
> I assume they work on the machine where the share is also mounted as drive a:\. It will probably stop working there as well as soon as you change the drive letter.

of course, that's obvious :) and the letter is valid only on that one windows machine - no doubt about it, this is how it works.

> This leads me to believe that the source of the problem is a commit that references a full path, even though it shouldn't
> (...)
> Just as a simple test, please move the `.git` folder somewhere else (...)

bingo! renamed `.git` folder for a second and Configurator started to work. so I searched all the files inside for the wrongly addressed `A:/` path. results? `.git/config` file contained `worktree = a:/` setting in the `[core]` part. commented that out & tried again. Configurator works without any problems.

so we've got a winner. don't know why, don't know how and when - but that `worktree` setting must have been entered automaticaly at some point. I've checked the docs & looks like it's not necessary anyway, so my problem is fixed for now 👍

thank you for the discussion & hints - that helped me to find the solution :)
