### ISSUE TITLE
Where is the settings.conf hidding?

### ISSUE THREAD

**Issue by TCPMeta** [danielperna84/hass-configurator#206]
Highly doubt anyone is willing to help and just point me to the Documentation like the other issue requests.

I am running Docker with Rancher/Kubernetes.

In the Container image where does the settings.conf file reside in? It's not populating in the volume I created for Configurator. I am also trying to fix the "Login attempt or request with invalid authentication from localhost (127.0.0.1) (Python-urllib/3.8)" issue.

**Comment by danielperna84** [comment]
The file isn't included in the image because it is not static - it's a config file. You have to create it yourself with the settings for your environment and map it into the container. Have a look at this: https://github.com/CausticLab/hass-configurator-docker#configuration (assuming you're using that image)
