### ISSUE TITLE
Slow loading/timeout when using SSL behind proxy

### ISSUE THREAD

**Issue by roflcoopter** [danielperna84/hass-configurator#39]
Hi!

I am experiencing a strange problem when trying to access the server on my RPi3 when i am behind a proxy using self signed SSL.

Trying to access through Chrome does not work, since it times out after 30 seconds. On the other hand, if i try it in Internet Explorer, it loads for a really long time usually around 300 seconds and then i am prompted for the password. 

The same applies when trying to switch the file to edit, here you can see an example from IEs developer tools under the Network Tab. First getting a file then saving it, both over 300 sec
![image](https://cloud.githubusercontent.com/assets/26493864/26206789/05cde24e-3be6-11e7-9983-1ddd4cf71f42.png)

So somehow it works, it just takes a really long time. If i disable SSL i am being prompted instantly for the username and password, but obviously its not a good idea to log in unencrypted.

Any idea what could be the cause of this?

**Comment by danielperna84** [comment]
By proxy, do you mean a reverse proxy that sits in front of the configurator, or do you mean a caching forward proxy?

**Comment by roflcoopter** [comment]
Due to lack of knowledge on the terminology ill clarify, 

My RPI is on my home network with no proxy, using self signed SSL from LetsEncrypt.

When trying to connect from my office, which is using a proxy i get the issues mentioned above.

If I turn off SSL i can connect to my RPi just fine

**Comment by danielperna84** [comment]
In that case I would assume that's a limitation that's caused by the proxy that's used in the office. When configuring a proxy you can control which type of connections may pass at given ports. For SSL that CONNECT method is used, which usually is only available on the ports 443 and 8443. Hence connecting to 3218 via SSL may not be allowed.
To confirm my theory, could you please try to use the configurator from some other place where no proxy is in between?

**Comment by roflcoopter** [comment]
Yupp, access from my phone for example works. I find it strange that it does work sometimes tho, but with the 300+sec response time

**Comment by danielperna84** [comment]
Since it's a company network there may be policies which IE uses automatically, but don't affect Chrome. Essentially this all boils down to being a local issue with the configuration of the network at your office. To get it fixed you have to reach out to the IT department (or whoever takes care of such things). As said before, the reason for the connectivity problems is probably caused by a restrictive policy within the proxy configuration.

**Comment by roflcoopter** [comment]
Seems reasonable, thanks for your input!
