### ISSUE TITLE
Split files and write a compile script

### ISSUE THREAD

**Issue by AtoxIO** [danielperna84/hass-configurator#67]
I understand wanting to use a single file, it's a very easy way to spread it around. However the main file keeps growing larger, and is becoming cumbersome to edit. In the past I've used scripts that would stitch everything together for these types of one-file projects. So what do you think about splitting the configurator.py like a regular project and adding a compile script to be run during pre-commit, or at release time, that assembles configurator.py? This way dev.html would also be simpler to maintain.

**Comment by danielperna84** [comment]
I have no experience of that kind. If there's a possibility to split files for development but still allow people to download just a single executable I'm open for that. My highest priority is to keep the setup as simple as possible. On quite a few occasions I had to support people who had trouble to just get the single file running. On top of that, the hass.io add-on actually pulls the raw configurator.py as well. Althouth that wouldn't be a big problem, since with the add-on there can be more sophisticated scripting to get things running. But seeing unexperienced users struggle with just a single file stops me from making this more "complicated".

So, yeah, if you point me at possible solutions that could make things easier I'll have a look at that.
Also: using the dev.html is actually working really nice. Just set the boolean to `True` in the configurator, do whatever you want in the .py-file, and changes appear without restarting the executable. And when done just copy the content of dev.html into the .py. That's how @jmart518 brought us the material design.

**Comment by danielperna84** [comment]
Since future versions will only be distributed as a pip package I am able to include multiple files, and therefore split everything up. To me this fixes the issue as soon as the devel branch gets merged into master.

**Comment by danielperna84** [comment]
Since (some) files are now split and packaged this issue has become obsolete.
