### ISSUE TITLE
Lock configurator into basepath (pretend chroot)

### ISSUE THREAD

**Issue by AtoxIO** [danielperna84/hass-configurator#68]
Would it be useful to implement a method to lock the user into the basepath? This would be a plus for security, and probably not all that hard to implement.

Implementation wise it would be as simple as checking the user-requested dir for attack vectors (like ..) and prepending the basepath to it in the backend at all times. Most other web based file managers use this approach.

Though the attack surface through the home-assistant configuration files remains huge, this would make hass-configurator useful as a general purpose configuration manager.

**Comment by danielperna84** [comment]
I actually use the configurator intentionally outside the scope of the basepath because I'm often to lazy to ssh+vim into linux machines. I even use it on non-hass machines. So if this would be implemented, then only optionally. I do like to have the basepath pointing to my hass-config (because that's what I do the most) + being able to modify other files. So just enforcing the basepath wouldn't be the best solution. How about a boolean setting like `ENFORCE_BASEPATH`?

**Comment by TheZoker** [comment]
@danielperna84 That would be nice!
