### ISSUE TITLE
Why depend on CDN resources, preventing offline use?

### ISSUE THREAD

**Issue by iron8core** [danielperna84/hass-configurator#73]
I'm not that knowledgeable when it comes to HTML/JS, but as the subject says: Why depend on non-local resources? Wouldn't it be better to include these in the addon?

Sorry if this is a stupid question, but even https://home-assistant.io/hassio/ say "100% local home automation". I realize this is an addon though so that might not apply.

Regardless, thanks for a great addon.

**Comment by danielperna84** [comment]
The reason is, that the configurator primarily is a standalone application that only happens to also have become a hassio addon. And the standalone version ist developed in a way that makes it very easy to install. It's just a single file you have to download and execute. Packaging all the external dependencies would make it more difficult for beginners to get this running. And including them plaintext within this one file would make this already huge file even bigger.

Also, the configurator itself is working offline. It's no problem at all if the machine it is running on has no internet access. It's the clients browser that is downloading the dependencies. And usually the clients will have a working internet connection.

And yes, the "100%..." doesn't always apply to the available addons. Some even don't make any sense without having a working internet connection.
