### ISSUE TITLE
How to set GIT https password

### ISSUE THREAD

**Issue by jwbaart** [danielperna84/hass-configurator#84]
I'm trying to use the GIT functionality in the configurator of Hass.io. But when I try to push my changes:

- Execute shell command
- git push -u origin master

It won't prompt for my github password and fails with the error:

   fatal: could not read Password for 'https://jwbaart@github.com': No such device or address

**Comment by danielperna84** [comment]
The git integration in the configurator is rather basic. It works with repositories that are reachable via SSH. For that pubkey authentication can be used. The general problem is, that nothing interactive (for entering credentials) can be done without making the configurator a lot more complicated.
The used [GitPython](https://gitpython.readthedocs.io/en/stable/) module has no direct support to use credentials either. There seem to be manual workarounds, but I haven't looked deeper into that. I can't even test it because my GitHub is secured with 2FA, which is a whole different thing.
So your only choice would be to push changes to a local ssh-repository and push the changes from there to GitHub.

**Comment by jwbaart** [comment]
That explains, thanks for you explanation!
