### ISSUE TITLE
errors when trying to run script in docker

### ISSUE THREAD

**Issue by ianhyzy** [danielperna84/hass-configurator#97]
I have HASS installed in the docker container running on a Synology NAS. The container has python 3.6 and runs homeassistant fine, but I get errors when trying to run the configurator script:

![image](https://user-images.githubusercontent.com/3400872/40738938-7bcb0c68-640a-11e8-99e3-d90963dd9378.png)

After that, I looked up my python path and tried changing  the script to match but that also didn't work. 
![image](https://user-images.githubusercontent.com/3400872/40738975-9858e1d4-640a-11e8-8842-e4a43b67155e.png)

Any help is appreciated.

**Comment by danielperna84** [comment]
You shouldn't put the configurator script in the HASS container. That would break everything as soon as you update the HASS container.
There is a ready to use container for the HASS Configurator: https://github.com/CausticLab/hass-configurator-docker
Also you have to do is share the volume where HASS stores the configuration.

Other than that I can't really help with that since I don't know much about Docker.

**Comment by ianhyzy** [comment]
Thanks, I'll check that out!
